package employeemanagementsystem;

import javax.swing.table.*;
import java.io.*;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */



public class MainJFrame extends javax.swing.JFrame {
    private DefaultTableModel model;
    public HashTable theHT;
    
    public MainJFrame() {
        initComponents();
        initOtherComponents();
        initHashTable();
        refreshDisplayTable();
  
    }

    public void initOtherComponents(){
        employeeAddedLabel.setVisible(false);
        displayTable.setVisible(false);
        displayTableScrollPane.setVisible(false);
        empNotFoundLabel.setVisible(false);
        empEditPanel.setVisible(false);
        editResponseLabel.setVisible(false);
    }
    
    private void initHashTable(){
        try{
            FileInputStream fis = new FileInputStream("database.txt");
            ObjectInputStream ois = new ObjectInputStream(fis);
            theHT = (HashTable) ois.readObject();
            if(theHT == null){
                theHT = new HashTable(10);
                System.out.println("Initializing new HashTable.");
            } else {
                System.out.println("HashTable successfully deserialized.");
            }
            ois.close();
            fis.close();
        } catch(EOFException e){
            System.out.println(e);
        } catch(Exception e){
            System.out.println(e);
        }
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jColorChooser1 = new javax.swing.JColorChooser();
        title = new java.awt.Label();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        addPanel = new javax.swing.JPanel();
        fullTimeEmployeeAddButton = new javax.swing.JRadioButton();
        partTimeEmployeeAddButton = new javax.swing.JRadioButton();
        employeeNumberAddLabel = new javax.swing.JLabel();
        firstNameAddLabel = new javax.swing.JLabel();
        lastNameAddLabel = new javax.swing.JLabel();
        genderAddLabel = new javax.swing.JLabel();
        workLocationAddLabel = new javax.swing.JLabel();
        deductionRateAddLabel = new javax.swing.JLabel();
        employeeNumberAddTextField = new javax.swing.JTextField();
        firstNameAddTextField = new javax.swing.JTextField();
        lastNameAddTextField = new javax.swing.JTextField();
        genderAddTextField = new javax.swing.JTextField();
        workLocationAddTextField = new javax.swing.JTextField();
        deductionRateAddTextField = new javax.swing.JTextField();
        addPanelDivider = new javax.swing.JSeparator();
        wageAddLabel = new javax.swing.JLabel();
        wageAddTextField = new javax.swing.JTextField();
        hoursPerWeekAddLabel = new javax.swing.JLabel();
        hoursPerWeekAddTextField = new javax.swing.JTextField();
        weeksPerYearAddLabel = new javax.swing.JLabel();
        weeksPerYearAddTextField = new javax.swing.JTextField();
        wageTitle = new javax.swing.JLabel();
        addEmployeeButton = new javax.swing.JButton();
        resetAddButton = new javax.swing.JButton();
        employeeAddedLabel = new javax.swing.JLabel();
        generalInformationTitle = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        searchEmpNumberLabel = new javax.swing.JLabel();
        searchEmpTextField = new javax.swing.JTextField();
        searchEmpButton = new javax.swing.JButton();
        clearSearchEmpButton = new javax.swing.JButton();
        empNotFoundLabel = new javax.swing.JLabel();
        empEditPanel = new javax.swing.JPanel();
        partTimeEmployeeEditButton = new javax.swing.JRadioButton();
        fullTimeEmployeeEditButton = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        generalInformationEditLabel = new javax.swing.JLabel();
        employeeNumberEditLabel = new javax.swing.JLabel();
        employeeNumberEditTextField = new javax.swing.JTextField();
        firstNameEditLabel = new javax.swing.JLabel();
        firstNameEditTextField = new javax.swing.JTextField();
        lastNameEditLabel = new javax.swing.JLabel();
        lastNameEditTextField = new javax.swing.JTextField();
        genderEditLabel = new javax.swing.JLabel();
        workLocationEditLabel = new javax.swing.JLabel();
        workLocationEditTextField = new javax.swing.JTextField();
        deductionRateEditLabel = new javax.swing.JLabel();
        deductionRateEditTextField = new javax.swing.JTextField();
        salaryInfoEditLabel = new javax.swing.JLabel();
        wageEditLabel = new javax.swing.JLabel();
        wageEditTextField = new javax.swing.JTextField();
        hPWEditLabel = new javax.swing.JLabel();
        hPWEditTextField = new javax.swing.JTextField();
        wPYEditLabel = new javax.swing.JLabel();
        wPYEditTextField = new javax.swing.JTextField();
        saveChangesButton = new javax.swing.JButton();
        deleteEmployeeButton = new javax.swing.JButton();
        genderEditTextField = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        editResponseLabel = new javax.swing.JLabel();
        overviewPanel = new javax.swing.JPanel();
        displayTableScrollPane = new javax.swing.JScrollPane();
        displayTable = new javax.swing.JTable();
        refreshTableButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        title.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        title.setText("Abhinav's Employee Management System");

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setToolTipText("");

        addPanel.setToolTipText("Add");
        addPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fullTimeEmployeeAddButton.setText("Full Time Employee");
        fullTimeEmployeeAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullTimeEmployeeAddButtonActionPerformed(evt);
            }
        });
        addPanel.add(fullTimeEmployeeAddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 44, 137, -1));

        partTimeEmployeeAddButton.setSelected(true);
        partTimeEmployeeAddButton.setText("Part Time Employee");
        partTimeEmployeeAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partTimeEmployeeAddButtonActionPerformed(evt);
            }
        });
        addPanel.add(partTimeEmployeeAddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 18, 137, -1));

        employeeNumberAddLabel.setText("Employee Number");
        addPanel.add(employeeNumberAddLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 109, -1, -1));

        firstNameAddLabel.setText("First Name");
        addPanel.add(firstNameAddLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 147, -1, -1));

        lastNameAddLabel.setText("Last Name");
        addPanel.add(lastNameAddLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 172, -1, -1));

        genderAddLabel.setText("Gender");
        addPanel.add(genderAddLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 210, -1, -1));

        workLocationAddLabel.setText("Work Location");
        addPanel.add(workLocationAddLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 238, -1, -1));

        deductionRateAddLabel.setText("Deduction Rate");
        addPanel.add(deductionRateAddLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 269, -1, -1));

        employeeNumberAddTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        addPanel.add(employeeNumberAddTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 106, 156, -1));

        firstNameAddTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        addPanel.add(firstNameAddTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 144, 156, -1));

        lastNameAddTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        addPanel.add(lastNameAddTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 172, 156, -1));

        genderAddTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        addPanel.add(genderAddTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 210, 156, -1));

        workLocationAddTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        addPanel.add(workLocationAddTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 235, 156, -1));

        deductionRateAddTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        addPanel.add(deductionRateAddTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 266, 156, -1));

        addPanelDivider.setOrientation(javax.swing.SwingConstants.VERTICAL);
        addPanel.add(addPanelDivider, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 16, 13, 270));

        wageAddLabel.setText("Hourly Wage");
        addPanel.add(wageAddLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 108, -1, -1));

        wageAddTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        addPanel.add(wageAddTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 105, 109, -1));

        hoursPerWeekAddLabel.setText("Hours / Week");
        addPanel.add(hoursPerWeekAddLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 139, -1, -1));

        hoursPerWeekAddTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        addPanel.add(hoursPerWeekAddTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 136, 109, -1));

        weeksPerYearAddLabel.setText("Weeks / Year");
        addPanel.add(weeksPerYearAddLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 170, -1, -1));

        weeksPerYearAddTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        addPanel.add(weeksPerYearAddTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 167, 109, -1));

        wageTitle.setText("Salary/Wages Information");
        addPanel.add(wageTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 80, -1, -1));

        addEmployeeButton.setText("Add Employee");
        addEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeButtonActionPerformed(evt);
            }
        });
        addPanel.add(addEmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 270, -1));

        resetAddButton.setText("Reset");
        resetAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetAddButtonActionPerformed(evt);
            }
        });
        addPanel.add(resetAddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 280, -1));

        employeeAddedLabel.setForeground(new java.awt.Color(34, 134, 34));
        employeeAddedLabel.setText("Employee # Successfully Added!");
        addPanel.add(employeeAddedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, -1, -1));

        generalInformationTitle.setText("General Information");
        addPanel.add(generalInformationTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 81, -1, -1));

        jTabbedPane1.addTab("Add", addPanel);

        searchEmpNumberLabel.setText("Employee Number:");

        searchEmpTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEmpTextFieldActionPerformed(evt);
            }
        });

        searchEmpButton.setText("Search");
        searchEmpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEmpButtonActionPerformed(evt);
            }
        });

        clearSearchEmpButton.setText("Clear");
        clearSearchEmpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearSearchEmpButtonActionPerformed(evt);
            }
        });

        empNotFoundLabel.setForeground(new java.awt.Color(250, 0, 0));
        empNotFoundLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empNotFoundLabel.setText("Sorry, employee not found");

        partTimeEmployeeEditButton.setSelected(true);
        partTimeEmployeeEditButton.setText("Part Time");
        partTimeEmployeeEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partTimeEmployeeEditButtonActionPerformed(evt);
            }
        });

        fullTimeEmployeeEditButton.setText("Full Time");
        fullTimeEmployeeEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullTimeEmployeeEditButtonActionPerformed(evt);
            }
        });

        generalInformationEditLabel.setText("General Information");

        employeeNumberEditLabel.setText("Employee Number");

        employeeNumberEditTextField.setText("[Number]");
        employeeNumberEditTextField.setEnabled(false);
        employeeNumberEditTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeNumberEditTextFieldActionPerformed(evt);
            }
        });

        firstNameEditLabel.setText("First Name");

        firstNameEditTextField.setText("[First Name]");

        lastNameEditLabel.setText("Last Name");

        lastNameEditTextField.setText("[Last Name]");
        lastNameEditTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameEditTextFieldActionPerformed(evt);
            }
        });

        genderEditLabel.setText("Gender");

        workLocationEditLabel.setText("Work Location");

        workLocationEditTextField.setText("[Work Location]");

        deductionRateEditLabel.setText("Deduction Rate");

        deductionRateEditTextField.setText("[Deduction Rate]");

        salaryInfoEditLabel.setText("Salary/Wages Information");

        wageEditLabel.setText("Hourly Wage");

        wageEditTextField.setText("[Hourly Wage]");

        hPWEditLabel.setText("Hours Per Week");

        hPWEditTextField.setText("[Hours Per Week]");

        wPYEditLabel.setText("Weeks Per Year");

        wPYEditTextField.setText("[Weeks Per Year]");

        saveChangesButton.setText("Save Changes");
        saveChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveChangesButtonActionPerformed(evt);
            }
        });

        deleteEmployeeButton.setText("Delete Employee");
        deleteEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEmployeeButtonActionPerformed(evt);
            }
        });

        genderEditTextField.setText("[Gender]");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout empEditPanelLayout = new javax.swing.GroupLayout(empEditPanel);
        empEditPanel.setLayout(empEditPanelLayout);
        empEditPanelLayout.setHorizontalGroup(
            empEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empEditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(empEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(empEditPanelLayout.createSequentialGroup()
                        .addGroup(empEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fullTimeEmployeeEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameEditLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(empEditPanelLayout.createSequentialGroup()
                        .addGroup(empEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(empEditPanelLayout.createSequentialGroup()
                                .addGroup(empEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(empEditPanelLayout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addComponent(generalInformationEditLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(empEditPanelLayout.createSequentialGroup()
                                        .addGroup(empEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(empEditPanelLayout.createSequentialGroup()
                                                .addGroup(empEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(deductionRateEditLabel)
                                                    .addComponent(employeeNumberEditLabel)
                                                    .addComponent(workLocationEditLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(empEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(workLocationEditTextField)
                                                    .addComponent(firstNameEditTextField)
                                                    .addComponent(employeeNumberEditTextField)
                                                    .addComponent(deductionRateEditTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)))
                                            .addGroup(empEditPanelLayout.createSequentialGroup()
                                                .addComponent(lastNameEditLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lastNameEditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, empEditPanelLayout.createSequentialGroup()
                                                .addComponent(genderEditLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(genderEditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(empEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(empEditPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(empEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(wPYEditLabel)
                                            .addComponent(hPWEditLabel)
                                            .addComponent(wageEditLabel))
                                        .addGap(48, 48, 48)
                                        .addGroup(empEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(wageEditTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(hPWEditTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(wPYEditTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(empEditPanelLayout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addComponent(salaryInfoEditLabel))))
                            .addGroup(empEditPanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(saveChangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(deleteEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(271, 271, 271))
                    .addGroup(empEditPanelLayout.createSequentialGroup()
                        .addComponent(partTimeEmployeeEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        empEditPanelLayout.setVerticalGroup(
            empEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empEditPanelLayout.createSequentialGroup()
                .addGroup(empEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(empEditPanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(empEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(empEditPanelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(empEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(empEditPanelLayout.createSequentialGroup()
                                        .addComponent(wageEditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hPWEditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(wPYEditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(empEditPanelLayout.createSequentialGroup()
                                        .addGroup(empEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(employeeNumberEditLabel)
                                            .addComponent(employeeNumberEditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(empEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(firstNameEditLabel)
                                            .addComponent(firstNameEditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addGroup(empEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lastNameEditLabel)
                                            .addComponent(lastNameEditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(empEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(genderEditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(genderEditLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(empEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(workLocationEditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(workLocationEditLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(empEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(deductionRateEditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deductionRateEditLabel)))))
                    .addGroup(empEditPanelLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(partTimeEmployeeEditButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fullTimeEmployeeEditButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(empEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(empEditPanelLayout.createSequentialGroup()
                                .addComponent(salaryInfoEditLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(wageEditLabel)
                                .addGap(15, 15, 15)
                                .addComponent(hPWEditLabel))
                            .addComponent(generalInformationEditLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(wPYEditLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(empEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveChangesButton)
                    .addComponent(deleteEmployeeButton))
                .addContainerGap())
        );

        editResponseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editResponseLabel.setText("Employee sucessfully edited");

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(empNotFoundLabel)
                .addGap(223, 223, 223))
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empEditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(searchPanelLayout.createSequentialGroup()
                                .addComponent(searchEmpNumberLabel)
                                .addGap(18, 18, 18)
                                .addComponent(searchEmpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(clearSearchEmpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchEmpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(editResponseLabel)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchEmpNumberLabel)
                    .addComponent(searchEmpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchEmpButton)
                    .addComponent(clearSearchEmpButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(empNotFoundLabel)
                .addGap(18, 18, 18)
                .addComponent(empEditPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editResponseLabel)
                .addGap(6, 6, 6))
        );

        jTabbedPane1.addTab("Search", searchPanel);

        displayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        displayTableScrollPane.setViewportView(displayTable);

        refreshTableButton.setText("Refresh Table");
        refreshTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTableButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout overviewPanelLayout = new javax.swing.GroupLayout(overviewPanel);
        overviewPanel.setLayout(overviewPanelLayout);
        overviewPanelLayout.setHorizontalGroup(
            overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overviewPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(displayTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                    .addComponent(refreshTableButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        overviewPanelLayout.setVerticalGroup(
            overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overviewPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(refreshTableButton)
                .addGap(18, 18, 18)
                .addComponent(displayTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Overview", overviewPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeButtonActionPerformed

        try{
            int newEmpNumber = Integer.parseInt(employeeNumberAddTextField.getText());
            String newEmpFN = firstNameAddTextField.getText();
            String newEmpLN = lastNameAddTextField.getText();
            String newEmpGender = genderAddTextField.getText();
            String newEmpWL = workLocationAddTextField.getText();
            double newEmpDR = Double.parseDouble(deductionRateAddTextField.getText());
            double newEmpWage = Double.parseDouble(wageAddTextField.getText());
            
            if(theHT.searchEmployeeNumber(newEmpNumber) == null){
            
                if(partTimeEmployeeAddButton.isSelected()){
                   double newEmpHPW = Double.parseDouble(hoursPerWeekAddTextField.getText());
                   double newEmpWPY = Double.parseDouble(weeksPerYearAddTextField.getText());
                   PTE newEmployee = new PTE(newEmpNumber, newEmpFN, newEmpLN, newEmpGender, newEmpWL, newEmpDR, newEmpWage, newEmpHPW, newEmpWPY);
                   theHT.addEmployee(newEmployee);
                } else { //creates new FTE
                    FTE newEmployee = new FTE(newEmpNumber, newEmpFN, newEmpLN, newEmpGender, newEmpWL, newEmpDR, newEmpWage);
                    theHT.addEmployee(newEmployee);
                } 
                employeeAddedLabel.setText("Employee #" + newEmpNumber + " added to the system!");
                employeeAddedLabel.setVisible(true);

                employeeNumberAddTextField.setText("");
                firstNameAddTextField.setText("");   
                lastNameAddTextField.setText("");
                genderAddTextField.setText("");
                workLocationAddTextField.setText("");
                deductionRateAddTextField.setText("");
                wageAddTextField.setText("");
                hoursPerWeekAddTextField.setText("");
                weeksPerYearAddTextField.setText("");
            
            
            
            } else {
                employeeAddedLabel.setVisible(true);
                employeeAddedLabel.setText("Sorry that employee number is already taken.");
            }
            //creates new PTE
            
        } catch(Exception e){
            employeeAddedLabel.setText(e.toString());
            employeeAddedLabel.setVisible(true);
        }
        //creates variables for new employee
        
        
        
    }//GEN-LAST:event_addEmployeeButtonActionPerformed

    private void fullTimeEmployeeAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullTimeEmployeeAddButtonActionPerformed
        partTimeEmployeeAddButton.setSelected(false);
        fullTimeEmployeeAddButton.setSelected(true);
        hoursPerWeekAddLabel.setVisible(false);
        weeksPerYearAddLabel.setVisible(false);
        hoursPerWeekAddTextField.setVisible(false);
        weeksPerYearAddTextField.setVisible(false);
        wageAddLabel.setText("Salary");
    }//GEN-LAST:event_fullTimeEmployeeAddButtonActionPerformed

    private void partTimeEmployeeAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partTimeEmployeeAddButtonActionPerformed
        partTimeEmployeeAddButton.setSelected(true);  
        fullTimeEmployeeAddButton.setSelected(false);
        hoursPerWeekAddLabel.setVisible(true);
        weeksPerYearAddLabel.setVisible(true);
        hoursPerWeekAddTextField.setVisible(true);
        weeksPerYearAddTextField.setVisible(true);
        wageAddLabel.setText("Hourly Wage");
    }//GEN-LAST:event_partTimeEmployeeAddButtonActionPerformed

    private void resetAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetAddButtonActionPerformed
        employeeNumberAddTextField.setText("");
        firstNameAddTextField.setText("");   
        lastNameAddTextField.setText("");
        genderAddTextField.setText("");
        workLocationAddTextField.setText("");
        deductionRateAddTextField.setText("");
        wageAddTextField.setText("");
        hoursPerWeekAddTextField.setText("");
        weeksPerYearAddTextField.setText("");
        employeeAddedLabel.setVisible(false);
    }//GEN-LAST:event_resetAddButtonActionPerformed

    private void refreshTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTableButtonActionPerformed
        refreshDisplayTable();        // TODO add your handling code here:
    }//GEN-LAST:event_refreshTableButtonActionPerformed

    private void searchEmpTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEmpTextFieldActionPerformed
        
       
       
    }//GEN-LAST:event_searchEmpTextFieldActionPerformed

    private void partTimeEmployeeEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partTimeEmployeeEditButtonActionPerformed
        setPTE();
    }//GEN-LAST:event_partTimeEmployeeEditButtonActionPerformed

    private void setPTE(){
        partTimeEmployeeEditButton.setSelected(true);  
        fullTimeEmployeeEditButton.setSelected(false);
        hPWEditLabel.setVisible(true);
        wPYEditLabel.setVisible(true);
        hPWEditTextField.setVisible(true);
        wPYEditTextField.setVisible(true);
        wageEditLabel.setText("Hourly Wage");
    }
    
    private void setFTE(){
        partTimeEmployeeEditButton.setSelected(false);  
        fullTimeEmployeeEditButton.setSelected(true);
        hPWEditLabel.setVisible(false);
        wPYEditLabel.setVisible(false);
        hPWEditTextField.setVisible(false);
        wPYEditTextField.setVisible(false);
        wageEditLabel.setText("Salary");
    }
    
    private void employeeNumberEditTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeNumberEditTextFieldActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_employeeNumberEditTextFieldActionPerformed

    private void lastNameEditTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameEditTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameEditTextFieldActionPerformed

    private void deleteEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEmployeeButtonActionPerformed
        int newEmpNumber = Integer.parseInt(employeeNumberEditTextField.getText());
        theHT.removeEmployee(newEmpNumber);
        editResponseLabel.setText("Employee #" + newEmpNumber + " successfully deleted.");
        editResponseLabel.setVisible(true);
        empEditPanel.setVisible(false);
        searchEmpTextField.setText("");
        empNotFoundLabel.setVisible(false);
        
        
    }//GEN-LAST:event_deleteEmployeeButtonActionPerformed

    private void searchEmpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEmpButtonActionPerformed
        try {
            int empNum = Integer.parseInt(searchEmpTextField.getText());
            if(theHT.searchEmployeeNumber(empNum) == null){
                empNotFoundLabel.setVisible(true);
                empEditPanel.setVisible(false);
            } else {
                empEditPanel.setVisible(true);
                empNotFoundLabel.setVisible(false);
                EmployeeInfo searchedEmp = theHT.searchEmployeeNumber(empNum);
                employeeNumberEditTextField.setText(Integer.toString(searchedEmp.getEmpNum()));
                firstNameEditTextField.setText(searchedEmp.getFirstName());
                lastNameEditTextField.setText(searchedEmp.getLastName());
                genderEditTextField.setText(searchedEmp.gender);
                workLocationEditTextField.setText(searchedEmp.workLoc);
                deductionRateEditTextField.setText(Double.toString(searchedEmp.deductRate));
                if(searchedEmp instanceof PTE){
                    setPTE();
                    wageEditTextField.setText(Double.toString(((PTE) searchedEmp).hourlyWage));
                    hPWEditTextField.setText(Double.toString(((PTE) searchedEmp).hoursPerWeek));
                    wPYEditTextField.setText(Double.toString(((PTE) searchedEmp).weeksPerYear));
                } else {
                    setFTE();
                    wageEditTextField.setText(Double.toString(((FTE) searchedEmp).getYearlySalary()));
                }
                
            }
        } catch (Exception e){
           System.out.println(e);
        }
    }//GEN-LAST:event_searchEmpButtonActionPerformed

    private void fullTimeEmployeeEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullTimeEmployeeEditButtonActionPerformed
        setFTE();
    }//GEN-LAST:event_fullTimeEmployeeEditButtonActionPerformed

    private void clearSearchEmpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearSearchEmpButtonActionPerformed

        empEditPanel.setVisible(false);
        searchEmpTextField.setText("");
        empNotFoundLabel.setVisible(false);
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_clearSearchEmpButtonActionPerformed
    
    private void saveChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChangesButtonActionPerformed
        try{
            int newEmpNumber = Integer.parseInt(employeeNumberEditTextField.getText());
            String newEmpFN = firstNameEditTextField.getText();
            String newEmpLN = lastNameEditTextField.getText();
            String newEmpGender = genderEditTextField.getText();
            String newEmpWL = workLocationEditTextField.getText();
            Double newEmpDR = Double.parseDouble(deductionRateEditTextField.getText());
            Double newEmpWage = Double.parseDouble(wageEditTextField.getText());
            theHT.removeEmployee(newEmpNumber);
            
            if(partTimeEmployeeEditButton.isSelected()){
               Double newEmpHPW = Double.parseDouble(hPWEditTextField.getText());
               Double newEmpWPY = Double.parseDouble(wPYEditTextField.getText());
               PTE newEmployee = new PTE(newEmpNumber, newEmpFN, newEmpLN, newEmpGender, newEmpWL, newEmpDR, newEmpWage, newEmpHPW, newEmpWPY);
               theHT.addEmployee(newEmployee);
            } else { //creates new FTE
                FTE newEmployee = new FTE(newEmpNumber, newEmpFN, newEmpLN, newEmpGender, newEmpWL, newEmpDR, newEmpWage);
                theHT.addEmployee(newEmployee);
            } 
            editResponseLabel.setText("Employee #" + newEmpNumber + " sucessfully edited.");
            editResponseLabel.setVisible(true);

            employeeNumberEditTextField.setText("");
            firstNameEditTextField.setText("");   
            lastNameEditTextField.setText("");
            genderEditTextField.setText("");
            workLocationEditTextField.setText("");
            deductionRateEditTextField.setText("");
            wageEditTextField.setText("");
            hPWEditTextField.setText("");
            wPYEditTextField.setText("");
            empEditPanel.setVisible(false);
            searchEmpTextField.setText("");
     
        } catch(Exception e){
            editResponseLabel.setText(e.toString());
            editResponseLabel.setVisible(true);
        }
        //creates variables for new employee
    }//GEN-LAST:event_saveChangesButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try{
            FileOutputStream fos = new FileOutputStream("database.txt");
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            oos.writeObject(theHT);
            oos.close();
            fos.close();
            System.out.println("Changes saved to database.");
        } catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_formWindowClosing

    
    private void refreshDisplayTable() {                                         
        // TODO add your handling code here:
        displayTable.setVisible(true);
        displayTableScrollPane.setVisible(true);
        int numInHT = theHT.getNumInHashTable();
        
        model = new DefaultTableModel(new Object[] {"Emp Num",
                                                    "Status",
                                                    "First Name",
                                                    "Last Name",
                                                    "Work Location",
                                                    "Deduction Rate"},
                                                    numInHT);
        displayTable.setModel(model);
        displayTable.setAutoCreateColumnsFromModel(true);
            
        int empCounter = -1; // Row position in table for the employee
        
        //jTextField1.setText(Integer.toString(numInHT));
        System.out.println("");
        System.out.println("Number of employees in the HT is " + numInHT);
        
        if (numInHT > 0) {
            System.out.println("Here are the employees:");
            for (int i = 0; i < theHT.buckets.length; i++) {
                for (int j = 0; j < theHT.buckets[i].size(); j++) {
                    
                    EmployeeInfo theEmp = theHT.buckets[i].get(j);
                    
                    empCounter++;
                    
                    System.out.println("  Employee number " + Integer.toString(theEmp.getEmpNum()));
                    System.out.println("  First name, last name : " + theEmp.getFirstName() + " " + theEmp.getLastName());

                    if (theEmp instanceof FTE) {
                        FTE theFTE = (FTE) theEmp;
                        System.out.println("    That employee has gross yearly salary $" + Double.toString(theFTE.getYearlySalary()));
                        System.out.println("    That employee has net yearly income $" + Double.toString(theFTE.calcAnnualNetIncome()));
                        
                        model.setValueAt("Full Time", empCounter, 1);
                        model.setValueAt(theEmp.getEmpNum(), empCounter, 0);
                        model.setValueAt(theEmp.getFirstName(), empCounter, 2);
                        model.setValueAt(theEmp.getLastName(), empCounter, 3);
                        model.setValueAt(theEmp.getWorkLocation(), empCounter, 4);
                        model.setValueAt(theEmp.getDeductRate(), empCounter, 5);
                    }
                    
                    if (theEmp instanceof PTE) {
                        PTE thePTE = (PTE) theEmp;
                        System.out.println("    That employee has hourly wage $" + Double.toString(thePTE.hourlyWage));
                        System.out.println("    That employee has hours per week " + Double.toString(thePTE.hoursPerWeek));
                        System.out.println("    That employee has weeks per year " + Double.toString(thePTE.weeksPerYear));
                        
                        model.setValueAt("Part Time", empCounter, 1);
                        model.setValueAt(theEmp.getEmpNum(), empCounter, 0);
                        model.setValueAt(theEmp.getFirstName(), empCounter, 2);
                        model.setValueAt(theEmp.getLastName(), empCounter, 3);
                        model.setValueAt(theEmp.getWorkLocation(), empCounter, 4);
                        model.setValueAt(theEmp.getDeductRate(), empCounter, 5);

                   }
                }
            
            }           
        }

        else {
            System.out.println("Nothing in the HT!  Too bad so sad :-(");
        }
        
        System.out.println("\nTABLE ROW COUNT " + displayTable.getRowCount());
        System.out.println("\nTABLE COLUMN COUNT " + displayTable.getColumnCount());

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmployeeButton;
    private javax.swing.JPanel addPanel;
    private javax.swing.JSeparator addPanelDivider;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clearSearchEmpButton;
    private javax.swing.JLabel deductionRateAddLabel;
    private javax.swing.JTextField deductionRateAddTextField;
    private javax.swing.JLabel deductionRateEditLabel;
    private javax.swing.JTextField deductionRateEditTextField;
    private javax.swing.JButton deleteEmployeeButton;
    private javax.swing.JTable displayTable;
    private javax.swing.JScrollPane displayTableScrollPane;
    private javax.swing.JLabel editResponseLabel;
    private javax.swing.JPanel empEditPanel;
    private javax.swing.JLabel empNotFoundLabel;
    private javax.swing.JLabel employeeAddedLabel;
    private javax.swing.JLabel employeeNumberAddLabel;
    private javax.swing.JTextField employeeNumberAddTextField;
    private javax.swing.JLabel employeeNumberEditLabel;
    private javax.swing.JTextField employeeNumberEditTextField;
    private javax.swing.JLabel firstNameAddLabel;
    private javax.swing.JTextField firstNameAddTextField;
    private javax.swing.JLabel firstNameEditLabel;
    private javax.swing.JTextField firstNameEditTextField;
    private javax.swing.JRadioButton fullTimeEmployeeAddButton;
    private javax.swing.JRadioButton fullTimeEmployeeEditButton;
    private javax.swing.JLabel genderAddLabel;
    private javax.swing.JTextField genderAddTextField;
    private javax.swing.JLabel genderEditLabel;
    private javax.swing.JTextField genderEditTextField;
    private javax.swing.JLabel generalInformationEditLabel;
    private javax.swing.JLabel generalInformationTitle;
    private javax.swing.JLabel hPWEditLabel;
    private javax.swing.JTextField hPWEditTextField;
    private javax.swing.JLabel hoursPerWeekAddLabel;
    private javax.swing.JTextField hoursPerWeekAddTextField;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lastNameAddLabel;
    private javax.swing.JTextField lastNameAddTextField;
    private javax.swing.JLabel lastNameEditLabel;
    private javax.swing.JTextField lastNameEditTextField;
    private javax.swing.JPanel overviewPanel;
    private javax.swing.JRadioButton partTimeEmployeeAddButton;
    private javax.swing.JRadioButton partTimeEmployeeEditButton;
    private javax.swing.JButton refreshTableButton;
    private javax.swing.JButton resetAddButton;
    private javax.swing.JLabel salaryInfoEditLabel;
    private javax.swing.JButton saveChangesButton;
    private javax.swing.JButton searchEmpButton;
    private javax.swing.JLabel searchEmpNumberLabel;
    private javax.swing.JTextField searchEmpTextField;
    private javax.swing.JPanel searchPanel;
    private java.awt.Label title;
    private javax.swing.JLabel wPYEditLabel;
    private javax.swing.JTextField wPYEditTextField;
    private javax.swing.JLabel wageAddLabel;
    private javax.swing.JTextField wageAddTextField;
    private javax.swing.JLabel wageEditLabel;
    private javax.swing.JTextField wageEditTextField;
    private javax.swing.JLabel wageTitle;
    private javax.swing.JLabel weeksPerYearAddLabel;
    private javax.swing.JTextField weeksPerYearAddTextField;
    private javax.swing.JLabel workLocationAddLabel;
    private javax.swing.JTextField workLocationAddTextField;
    private javax.swing.JLabel workLocationEditLabel;
    private javax.swing.JTextField workLocationEditTextField;
    // End of variables declaration//GEN-END:variables
}
